// SPDX-License-Identifier: AGPL-3.0-or-later OR BUSL-1.1

//! macOS Hypervisor.framework backend — all methods generated by `define_backend!`.

use std::sync::Arc;

use amla_core::IrqFactory;

use crate::error::{Error, Result};

fn new_backend_pools(
    pool_size: usize,
    vcpu_count: u32,
    layout: amla_hvf::HardwareLayout,
    worker: amla_core::WorkerProcessConfig,
) -> amla_hvf::Result<amla_hvf::VmPools> {
    amla_hvf::VmPools::new(pool_size, vcpu_count, layout, worker)
}

define_backend!(amla_hvf);
