// SPDX-License-Identifier: AGPL-3.0-or-later OR BUSL-1.1

//! KVM backend for Linux — all methods generated by `define_backend!`.

use std::sync::Arc;

use amla_core::IrqFactory;

use crate::error::{Error, Result};

#[cfg(feature = "subprocess")]
fn new_backend_pools(
    pool_size: usize,
    vcpu_count: u32,
    layout: amla_kvm::HardwareLayout,
    worker: amla_core::WorkerProcessConfig,
) -> amla_kvm::Result<amla_kvm::VmPools> {
    amla_kvm::VmPools::new(pool_size, vcpu_count, layout, worker)
}

#[cfg(not(feature = "subprocess"))]
fn new_backend_pools(
    pool_size: usize,
    vcpu_count: u32,
    layout: amla_kvm::HardwareLayout,
    _worker: amla_core::WorkerProcessConfig,
) -> amla_kvm::Result<amla_kvm::VmPools> {
    amla_kvm::VmPools::new(pool_size, vcpu_count, layout)
}

define_backend!(amla_kvm);
