// SPDX-License-Identifier: AGPL-3.0-or-later OR BUSL-1.1

//! Stub backend for unsupported platforms — all methods generated by `define_backend!`.

use std::sync::Arc;

use amla_core::IrqFactory;

use crate::error::{Error, Result};

fn new_backend_pools(
    pool_size: usize,
    vcpu_count: u32,
    layout: amla_stub::HardwareLayout,
    _worker: amla_core::WorkerProcessConfig,
) -> amla_stub::Result<amla_stub::VmPools> {
    amla_stub::VmPools::new(pool_size, vcpu_count, layout)
}

define_backend!(amla_stub);
